/**
 * Export ABIs to shared/abi directory
 * Run: npx hardhat run scripts/export-abi.ts
 */

import * as fs from "fs";
import * as path from "path";

const CONTRACTS = ["AssetPassport", "EventRegistry"];
const ARTIFACTS_DIR = path.join(__dirname, "..", "artifacts", "contracts");
const OUTPUT_DIR = path.join(__dirname, "..", "..", "shared", "abi");

interface ContractABI {
    abi: unknown[];
    contractName: string;
}

async function main() {
    console.log("Exporting ABIs to shared/abi...\n");

    // Ensure output directory exists
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    const exportedContracts: { name: string; path: string }[] = [];

    for (const contractName of CONTRACTS) {
        const artifactPath = path.join(
            ARTIFACTS_DIR,
            `${contractName}.sol`,
            `${contractName}.json`
        );

        if (!fs.existsSync(artifactPath)) {
            console.warn(`Warning: Artifact not found for ${contractName}`);
            continue;
        }

        const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
        const abi = artifact.abi;

        // Write ABI as JSON
        const outputPath = path.join(OUTPUT_DIR, `${contractName}.json`);
        fs.writeFileSync(outputPath, JSON.stringify(abi, null, 2));
        console.log(`✓ Exported ${contractName}.json`);

        exportedContracts.push({ name: contractName, path: outputPath });
    }

    // Generate TypeScript index file
    const indexContent = generateIndexFile(exportedContracts);
    fs.writeFileSync(path.join(OUTPUT_DIR, "index.ts"), indexContent);
    console.log(`✓ Generated index.ts`);

    // Generate addresses file template
    const addressesContent = generateAddressesTemplate();
    const addressesPath = path.join(OUTPUT_DIR, "addresses.ts");
    if (!fs.existsSync(addressesPath)) {
        fs.writeFileSync(addressesPath, addressesContent);
        console.log(`✓ Generated addresses.ts template`);
    }

    console.log("\nDone! ABIs exported to shared/abi/");
}

function generateIndexFile(
    contracts: { name: string; path: string }[]
): string {
    const imports = contracts
        .map((c) => `import ${c.name}ABI from "./${c.name}.json";`)
        .join("\n");

    const exports = contracts.map((c) => `  ${c.name}ABI,`).join("\n");

    return `// Auto-generated by export-abi.ts
// Do not edit manually

${imports}
export { default as addresses } from "./addresses";

export {
${exports}
};

// Type exports
export type { AssetInfo, LifecycleEvent, EventType } from "./types";
`;
}

function generateAddressesTemplate(): string {
    return `// Contract addresses by network
// Update these after deployment

export interface ContractAddresses {
  assetPassport: string;
  eventRegistry: string;
}

const addresses: Record<string, ContractAddresses> = {
  // Sepolia testnet
  sepolia: {
    assetPassport: "", // TODO: Update after deployment
    eventRegistry: "", // TODO: Update after deployment
  },
  // Mainnet (future)
  mainnet: {
    assetPassport: "",
    eventRegistry: "",
  },
  // Local development
  localhost: {
    assetPassport: "",
    eventRegistry: "",
  },
};

export default addresses;
`;
}

main().catch((error) => {
    console.error(error);
    process.exit(1);
});

