// Auto-generated by export-abi.ts
// Do not edit manually

import AssetPassportABI from "./AssetPassport.json";
import EventRegistryABI from "./EventRegistry.json";
export { default as addresses } from "./addresses";

export {
  AssetPassportABI,
  EventRegistryABI,
};

// Type exports
export type { AssetInfo, LifecycleEvent, EventType } from "./types";
